// 插件总入口，按顺序加载所有模块
import "./constants.js";
import "./utils.js";
import "./floatBall.js";
import "./novelReader.js";
import "./chapterManager.js";
import "./knowledgeGraph.js";
import "./novelWrite.js";
import "./settings.js";
import "./main.js";
