// 插件总入口，按依赖顺序加载所有模块化文件，无需修改
import "./constants.js";
import "./utils.js";
import "./floatBall.js";
import "./novelReader.js";
import "./chapterManager.js";
import "./knowledgeGraph.js";
import "./novelWrite.js";
import "./settings.js";
import "./main.js";
